### ISSUE TITLE
这个LookinServer.framework 不支持bitcode，能提供一个支持 bitcode版本的吗

### ISSUE THREAD

**Issue by guohongwei719** [QMUI/LookinServer#1]
### 我引入到工程以后编译报错如下：

ld: bitcode bundle could not be generated because '/Users/guohongwei719/Desktop/Moments_iOS/JYMomentsModule/Example/Pods/LookinServer/LookinServer.framework/LookinServer' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/guohongwei719/Desktop/Moments_iOS/JYMomentsModule/Example/Pods/LookinServer/LookinServer.framework/LookinServer' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
## 提示这个LookinServer.framework 不支持bitcode，能提供一个支持 bitcode版本的吗？

**Comment by hughkli** [comment]
好的，我们会在下周发布的版本更新中实现，版本发布时我们会在这个 issue 下通知你。

**Comment by guohongwei719** [comment]
请问什么时候能提供呀，都两周了哦？

**Comment by hughkli** [comment]
你好，刚刚发布了更新 LookinServer (0.9.4)，试一下现在是否支持 bitcode 了？

如果是使用 CocoaPods 则运行 pod update 即可。
如果是手动嵌入则下载 https://cdn.lookin.work/download/framework/LookinServer-0-9-4.zip 并替换项目里的原 framework 文件即可。

注意，仅发布了 LookinServer 的更新，没有发布 Lookin 客户端的更新，因此在 Lookin 客户端里点击“检查更新”仍然会提示 0.9.3 是最新版本客户端，这是正常的。

**Comment by guohongwei719** [comment]
试过了，可以的，非常棒，谢谢！
