### ISSUE TITLE
点刷新页面为会调用viewWillAppear

### ISSUE THREAD

**Issue by jiemi** [QMUI/LookinServer#10]
![image](https://user-images.githubusercontent.com/14103123/64163513-fc3e1a00-ce73-11e9-853c-644f2760caed.png)
点刷新页面为会调用viewWillAppear 我viewWillAppear做了一个addChildViewController的操作 ChildViewController是外部初始化传进来的 没判断nil 然后触发了异常
![image](https://user-images.githubusercontent.com/14103123/64163756-6ce53680-ce74-11e9-9415-c748e907ad35.png)
所以为什么要调用viewWillAppear

**Comment by hughkli** [comment]
理论上刷新时不应该调用 viewWillAppear，我这边在 demo 或别的项目中测试也确实没有发现调用，所以也许是你的项目中有什么特殊处理？

但是在刷新时，确实需要遍历当前界面所有的 UIView 和 CALayer 并切换它们的 hidden 属性以获取它们在没有 subview/sublayer 时的截图（[相关代码位置](https://github.com/QMUI/LookinServer/blob/master/SourceCode/LookinServer/Category/CALayer%2BLookinServer.m#L112)），但不确定这点是否和你提到的这个问题有关系。

你可以发送一个可以重现该问题的最小 demo 文件给我们，也可以下载 LookinServer 源代码自己调试。
