### ISSUE TITLE
Feat request: 希望恢复通过断点的方式引入Lookin Framework

### ISSUE THREAD

**Issue by WymanY** [QMUI/LookinServer#102]
如题：公司因为一些原因魔改了pod 相关的东西，导致我们新加入公司的同事很难引入新的库。故希望恢复breakpoint的方式添加lookin Framework

**Comment by hughkli** [comment]
很难，因为 Xcode 的升级啥的，之前的方式没法用了，而新的方式我又不会。

可以考虑直接把 LookinServer 的源码放到项目里（通过一个编译宏控制不要在 Release 模式引入）
