### ISSUE TITLE
显示 CAGradientLayer

### ISSUE THREAD

**Issue by wfs498121294** [QMUI/LookinServer#103]
你好  我用pod集成 在真机上看不到图层 都是显示CAGradientLayer
如下图
https://i.nextnet.cc/2022/08/15/c00d8fd7f8063.png

**Comment by hughkli** [comment]
把 LookinServer 更新到最新的 1.0.6 版本试试？

**Comment by Xchn** [comment]
Xcode Version 15.0

**Comment by Xchn** [comment]
Xcode15.0 ，Mac端Lookin Version 1.0.2(9)，LookinSserver1.2.0版本 ，也有同样的问题，但是在LookinSserver1.1.8版本却没有这个问题，是什么原因导致的呢？

**Comment by hughkli** [comment]
> Xcode15.0 ，Mac端Lookin Version 1.0.2(9)，LookinSserver1.2.0版本 ，也有同样的问题，但是在LookinSserver1.1.8版本却没有这个问题，是什么原因导致的呢？

@Xchn 奇怪，我这边用 Xcode15.0 beta6 试了一下没有问题呀，也没有收到其他人的反馈，所以很难调试。
你可以构造一个可以重现该 Bug 的 Demo 项目发给我吗？

**Comment by Xchn** [comment]
使用LookinServer项目中自带Demo工程是没有问题的，我看看能不能构建一个Demo复现该问题

**Comment by Xchn** [comment]
@hughkli 应该是集成了多个Lookin导致的，一个低版本的，一个高版本的，将低版本移除后，可以正常展示了，奇怪的是，我将低版本再加进去还也没问题了😂

**Comment by hughkli** [comment]
> @hughkli 应该是集成了多个Lookin导致的，一个低版本的，一个高版本的，将低版本移除后，可以正常展示了，奇怪的是，我将低版本再加进去还也没问题了😂

可能是随机的……比如可能哪天突然就又坏掉了啥的
