### ISSUE TITLE
偶现这个Crash

### ISSUE THREAD

**Issue by suquan** [QMUI/LookinServer#106]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[LookinConnectionAttachment objectForKeyedSubscript:]: unrecognized selector sent to instance 0x282442a20'
<LookinConnectionAttachment: 0x282442a20>

**Comment by hughkli** [comment]
是 iOS Crash 了还是 Lookin 客户端 Crash 了？下次遇到的时候可以把完整的堆栈截个图看看吗？

**Comment by beta-yu** [comment]
> 
iOS 14.1
![image](https://user-images.githubusercontent.com/30454773/202098250-8d0502ae-b11e-41c7-9792-7cc1d685bc07.png)

**Comment by 1084233320** [comment]
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[LookinConnectionAttachment objectForKeyedSubscript:]: unrecognized selector sent to instance 0x282442a20'
> <LookinConnectionAttachment: 0x282442a20>



> 是iOS Crash了还是Lookin客户端Crash了？下次遇到的时候可以把完整的堆垛截图看吗？

iOS Crash了，没有具体的报错语句，直接崩到main了
<img width="566" alt="image" src="https://github.com/QMUI/LookinServer/assets/86813960/94d633b8-e469-4a5e-a155-b3b887e364a3">

**Comment by hughkli** [comment]
最新发布的 1.2.8 尝试修复了这个 Crash
