### ISSUE TITLE
1.0.9版本xcode13.2.1打包报错

### ISSUE THREAD

**Issue by 0xBa0** [QMUI/LookinServer#112]
hi 大佬，麻烦有空看看；

<img width="851" alt="image" src="https://user-images.githubusercontent.com/39689377/197718993-a23bbfe8-9e49-4444-85d2-e1792e912c21.png">

 error: invalid preprocessing directive
#elifdef LOOKIN_SERVER_TESTFLIGHT_SWIFT_ENABLED

LKS_TraceManager.m:20:9: fatal error: 'LookinServerTestflight/LookinServerTestflight-Swift.h' file not found
#import <LookinServerTestflight/LookinServerTestflight-Swift.h>

**Comment by hughkli** [comment]
奇怪，理论上你的项目里，LOOKIN_SERVER_TESTFLIGHT_SWIFT_ENABLED 这个宏不应该被定义。

你是通过什么方式集成 LookinServer 的？CocoaPods 吗？还是 SPM？

**Comment by 0xBa0** [comment]
> 奇怪，理论上你的项目里，LOOKIN_SERVER_TESTFLIGHT_SWIFT_ENABLED 这个宏不应该被定义。
> 
> 你是通过什么方式集成 LookinServer 的？CocoaPods 吗？还是 SPM？

通过CocoaPods

**Comment by hughkli** [comment]
> > 奇怪，理论上你的项目里，LOOKIN_SERVER_TESTFLIGHT_SWIFT_ENABLED 这个宏不应该被定义。
> > 你是通过什么方式集成 LookinServer 的？CocoaPods 吗？还是 SPM？
> 
> 通过CocoaPods

这么奇怪，把你项目的 Podfile.lock 里的 LookinServer 版本号截个图看看？类似下图
![image](https://user-images.githubusercontent.com/15059475/198183524-1d0e7ddb-9483-47a2-946f-91c92c5abb91.png)

**Comment by xuhaodong1** [comment]
一样的问题，版本号也一致
![image](https://user-images.githubusercontent.com/41474954/198193369-7699b4ca-43c6-49d0-a208-334800efa26d.png)
Xcode版本为13.2.1，在Xcode14.0.1版本表现正常

pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']

**Comment by hughkli** [comment]
居然跟 Xcode 版本有关系吗……我手头所有电脑的 Xcode 都是 14.0.1 版本了，所以不太好调试，就先不改了吧，看看其它网友们有没有类似反馈先。

如果目前影响到了你们的使用，你们可以考虑：
- 升级到 Xcode14
- Podfile 里去掉对于 Swift subspec 的引用
- 把 LookinServer 回退到 1.0.6 版本
- 你们自己使用能重现该 Bug 的环境研究一下为啥 LOOKIN_SERVER_TESTFLIGHT_SWIFT_ENABLED 这个宏被定义了？

**Comment by hughkli** [comment]
> 一样的问题，版本号也一致 ![image](https://user-images.githubusercontent.com/41474954/198193369-7699b4ca-43c6-49d0-a208-334800efa26d.png) Xcode版本为13.2.1，在Xcode14.0.1版本表现正常
> 
> pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']

我刚刚发布了 LookinServer 1.1.0 版本，有可能解决了你这个问题，再试试？

**Comment by xuhaodong1** [comment]
hi, 更新为1.1.0, 全局只有一个LOOKIN_SERVER_TESTFLIGHT_SWIFT_ENABLED宏, 但仍有 
Invalid preprocessing directive 错误
![image](https://user-images.githubusercontent.com/41474954/198540499-2278f67d-e15a-4e5e-b827-9203accd16c0.png)

**Comment by hughkli** [comment]
> directive

好吧，看起来是不支持 #elifdef 这个指令，我再改改

**Comment by hughkli** [comment]
发了 v1.1.1，应该能编译的过了吧。。。。

**Comment by 0xBa0** [comment]
> 发了 v1.1.1，应该能编译的过了吧。。。。

编译通过，没有问题
