### ISSUE TITLE
流水线打包失败

### ISSUE THREAD

**Issue by YunFei2015** [QMUI/LookinServer#117]
/LookinServer/Src/Main/Server/Others/LKSConfigManager.m:43:59: error: no visible @interface for 'NSArray' declares the selector 'lookin_filter:'
 NSArray *validClassList = [((NSArray *)classList) lookin_filter:^BOOL(id obj) {
                     ^
/Users/ferry8/Library/Developer/Xcode/DerivedData/DoctorBoxApp-/LookinServer/Src/Main/Server/Others/LKSConfigManager.m:112:26: error: property 'lks_hostView' not found on object of type 'CALayer *'
UIView *view = layer.lks_hostView;
                     ^
2 errors generated.

2023-01-12 10:39:20 我司流水线打包失败，原因如上，我用 swift package 集成的，配置了自动升级，我看昨天刚好升级了1.1.4，还请帮忙看一下，Xcode 14.0.1
我们流水线是自定义的环境宏，lookinServer 自带的配置不是仅 debug 环境才会集成吗？

**Comment by YunFei2015** [comment]
我把源码下到本地，改成 pod 本地集成，也是 build 报错，缺少NSArray 的类别文件。

**Comment by hughkli** [comment]
我看了一下，因为我代码写错了，忘了加一个编译宏，稍等，我现在改一下

**Comment by hughkli** [comment]
刚刚发了 v1.1.5，应该修复了：https://github.com/QMUI/LookinServer/releases/tag/1.1.5

**Comment by YunFei2015** [comment]
编译成功了，感谢。
