### ISSUE TITLE
andorid平台也有类似的功能库吗？

### ISSUE THREAD

**Issue by AndroidHensen** [QMUI/LookinServer#119]
想在android开发使用，是否有其他库可以用？

**Comment by hughkli** [comment]
Lookin 不支持 Android。那 Android 开发时有没有类似的软件呢？我问了 GPT，它是这么回答的：

“除了 Android Studio，还有其他一些工具可以帮助您查看和调试 Android 应用程序的布局。

1. Layout Inspector：Layout Inspector 是 Android Studio 自带的一个工具，它可以帮助您查看应用程序的布局层次结构、布局属性、布局文件等。您可以使用 Layout Inspector 来检查应用程序中的布局问题，并对其进行调试和优化。

2. Stetho：Stetho 是一个开源的 Android 应用程序调试工具，它可以帮助您查看应用程序的布局、网络请求、数据库等信息。您可以通过 Stetho 在 Chrome 开发者工具中查看应用程序的布局层次结构、布局属性等。

3. UI Automator Viewer：UI Automator Viewer 是 Android SDK 自带的一个工具，它可以帮助您查看应用程序的布局层次结构、布局属性、截图等。您可以使用 UI Automator Viewer 来检查应用程序中的布局问题，并对其进行调试和优化。

4. Facebook Sonar：Facebook Sonar 是一个开源的应用程序调试工具，它可以帮助您查看应用程序的布局、网络请求、数据库等信息。您可以通过 Sonar 在 Chrome 开发者工具中查看应用程序的布局层次结构、布局属性等。

这些工具都可以帮助您更轻松地查看和调试 Android 应用程序的布局，提高开发效率。”
