### ISSUE TITLE
macOS 10.15 提示已损坏 Prompt that the software is damaged

### ISSUE THREAD

**Issue by WonderJeffy** [QMUI/LookinServer#12]
<img width="420" alt="QQ20191011-101738@2x" src="https://user-images.githubusercontent.com/16150489/66619809-d2190e00-ec10-11e9-8c2f-6792b4ce15f1.png">

注意：安全性设置已改为“允许任何来源”
Note: Security settings have been changed to "Allow any source"

**Comment by hughkli** [comment]
找身边升级了 10.15 的朋友试了一下没有遇到该问题，后台也已经统计到有大量升级了 10.15 的用户可以正常使用 Lookin，所以也许是你的电脑某些设置问题？

可以尝试一下：
- 重新下载 [Lookin app](https://cdn.lookin.work/release/Lookin-0-9-3.zip)
- [google](https://www.google.com/search?q=macos+app+damaged&oq=macos+app+damaged&aqs=chrome..69i57j0l3.6079j0j4&sourceid=chrome&ie=UTF-8) 或百度一下试试？
