### ISSUE TITLE
Value of type 'NSObject' has no member 'lks_ivarTraces'

### ISSUE THREAD

**Issue by iamStephenFang** [QMUI/LookinServer#121]
## Expected Behavior
The project compiles properly.

项目正常通过编译。

## Actual Behavior
LKS_TraceManager+Extension.swift fails to compile on line 52.

LKS_TraceManager+Extension.swift 第52行无法通过编译。

```
value.lks_ivarTraces = (value.lks_ivarTraces ?? []) + [ivarTrace]
```

Error 报错
```
Value of type 'NSObject' has no member 'lks_ivarTraces'
```
<img width="875" alt="CleanShot 2023-05-10 at 18 30 23" src="https://github.com/QMUI/LookinServer/assets/40275062/f508afd1-e1e9-487c-8f88-4e90c7543cbc">

## Steps to Reproduce the Problem

Upgrade LookinServer to 1.1.6 using Swift Package Manager then compile the project

使用Swift Package Manager 或其他包管理工具升级 LookinServer 到 1.1.6 并编译项目
 

## Specifications

  - Version: 1.1.6
  - Platform: macOS 13.3.1 (a)
  - Xcode Version: 14.3 (14E222b)

**Comment by iamStephenFang** [comment]
SPM 的依赖关系是 ```LookinServer``` 依赖 ```LookinServerSwift```， ```LookinServerSwift``` 依赖 ```LookinServerBase```

![CleanShot 2023-05-10 at 19 12 07](https://github.com/QMUI/LookinServer/assets/40275062/9c1c45d8-6195-4ee7-a525-a117939fd9a8)

```LookinServerSwift``` 里的 ```LKS_SwiftTraceManager```找不到由```LookinServerBase```移动到```LookinServer```的```lks_ivarTraces```定义

需要尝试修改SPM文件

**Comment by lyleLH** [comment]
差不多昨天也碰到了这个问题。是我在项目添加了MJRefresh之后才发生的。weird

**Comment by jeffy-w** [comment]
the same problem +1

**Comment by hughkli** [comment]
I have just published v1.1.7 to fix this bug. Sorry for this.

抱歉，我刚刚发布了 v1.1.7，修复了这个 SPM 相关的 bug。
