### ISSUE TITLE
-[__NSCFConstantString lks_rgbaComponents]: unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by tanghan0328** [QMUI/LookinServer#124]
-[__NSCFConstantString lks_rgbaComponents]: unrecognized selector sent to instance 
不管我是使用1.0.6版本或者最新的1.1.7版本，每次使用都会出现这个错误，颜色应该是一个数组，但是这里获取的是一个字符串，导致每次都出错，是不是应该添加一下判断，如果是数组怎样处理，如果是字符串，怎样处理？

**Comment by tanghan0328** [comment]
<img width="1699" alt="image" src="https://github.com/QMUI/LookinServer/assets/14178715/77d3b7c6-c728-4b55-aa89-68b4e6443648">

**Comment by hughkli** [comment]
感谢，LookinServer 最新的 1.2.4 版本对该 Crash 加了保护。
