### ISSUE TITLE
pod install失败

### ISSUE THREAD

**Issue by HelloLiii** [QMUI/LookinServer#128]
我试过清除cocoapods缓存重新导入，但仍然会报失败。同时我复制这个git网址是可以打开的，但是一直没办法解决这个导入失败的问题。
<img width="568" alt="image" src="https://github.com/QMUI/LookinServer/assets/137759970/0fe76121-36d8-4745-b071-6337576aad19">

**Comment by hughkli** [comment]
貌似和 github 被墙有关，不过我没有相关经验。

试试这些解决方案：https://www.google.com.hk/search?q=pod+install+github+libressl&oq=pod+install+github+libressl+&aqs=chrome..69i57j33i160l2.9797j1j7&sourceid=chrome&ie=UTF-8
