### ISSUE TITLE
:configurations => ['Debug']

### ISSUE THREAD

**Issue by AllForOnesLove** [QMUI/LookinServer#129]
是否有某种情况会导致指定:configurations => ['Debug']的情况下，framwork 被带到商店包中？  我现在遇到了这样的情况，很奇怪，是否和pod版本有关？pod 1.12.1

**Comment by hughkli** [comment]
不太清楚，我这边没收到过类似的反馈

**Comment by AllForOnesLove** [comment]
大致了解了原因，基于公司业务现状，可能无法避免将 dev 下的 pod 产物带到生产环境，请问我是否可以将 lookin 本地化，在 LKS_ConnectionManager --> Trying to connect 时去拦截发起链接，防止在 release 中使用，期待您的解答！

**Comment by hughkli** [comment]
我觉得你们可以考虑直接把 LookinServer 源码复制到你们项目里，然后在 Debug 环境下定义一下 SHOULD_COMPILE_LOOKIN_SERVER 这个宏。
![screenshot-20230826-004212](https://github.com/QMUI/LookinServer/assets/15059475/2914de45-af85-495a-b6fc-9bc6efd3d9bd)
