### ISSUE TITLE
是否有计划提供约束查看和修改

### ISSUE THREAD

**Issue by wellcheng** [QMUI/LookinServer#13]
相比较 Reveal，缺少了这个功能

**Comment by hughkli** [comment]
<img width="519" alt="屏幕快照 2019-10-30 16 06 47" src="https://user-images.githubusercontent.com/15059475/67839740-51727100-fb2f-11e9-855c-bf12d8ce10c9.png">
明天或后台发布的新版本里会加入约束的查看功能
