### ISSUE TITLE
Xcode15 beta5 SPM安装后编译报错

### ISSUE THREAD

**Issue by chenfengfeng** [QMUI/LookinServer#131]
![WX20230728-013220@2x](https://github.com/QMUI/LookinServer/assets/6957977/d29bb127-e7ae-4b63-a420-70d6ca58b67a)

报错如图所示，麻烦看看

**Comment by canius** [comment]
https://github.com/QMUI/LookinServer/pull/127

**Comment by hughkli** [comment]
抱歉工作太忙了，刚看到。
我试了一下最新的 Xcode Beta 已经没有这个问题了，不过 beta5 确实有问题。
我把你的代码 merge 进来了。

感谢。
