### ISSUE TITLE
突然不能用了，也是很懵

### ISSUE THREAD

**Issue by xygkevin** [QMUI/LookinServer#132]
<img width="1296" alt="image" src="https://github.com/QMUI/LookinServer/assets/19592642/e836ef4e-7adb-465b-949a-0d7918991320">

**Comment by rakuyoMo** [comment]
同一时间只能一个 App 连接 LookinServer，您这个应该是打开了多个 App，所以 Lookin 端口都被占用了。只保留一个就好了。

**Comment by hughkli** [comment]
其实这是 LookinServer 的一个历史悠久的 Bug，只要你不停地把你的 App 在前台和后台之间来回切换，切换个 4、5 次，就会遇到这种状况。

估计我代码里哪个标记位写错了……唉，打工之外找时间修吧
