### ISSUE TITLE
 'Swift' subspec 和 'NoHook' subspec 没法同时引入

### ISSUE THREAD

**Issue by sunimp** [QMUI/LookinServer#134]
具体来讲，在指定了 `:configurations => ['Debug']` 后，CocoaPods 就不支持多 subspecs 的引入，即：

`pod 'LookinServer', :subspecs => ['Swift', 'NoHook'], :configurations => ['Debug']`

在 `pod install` 时会报错：
>[!] The subspecs of `LookinServer` are linked to different build configurations for the `Pods-YourProject` target. CocoaPods does not currently support subspecs across different build configurations.

**Comment by hughkli** [comment]
没想到 cocoapods 还有这种限制……我现在改改，分成 Swift, NoHook, SwiftAndNoHook 三个 subspec

**Comment by hughkli** [comment]
我刚刚发了 1.2.0（可能要等个半小时待 CocoaPods 刷新数据），增加了 SwiftAndNoHook 这个 subspec，你可以试试。
