### ISSUE TITLE
crash with 'SwiftAndNoHook'

### ISSUE THREAD

**Issue by 0xBa0** [QMUI/LookinServer#136]
version: 1.2.1
必现

-[CALayer(LookinServer) lks_groupScreenshotWithLowQuality:]
contentSize为.zero 时，触发断言

<img width="1891" alt="WeChatWorkScreenshot_08032d06-bedb-4ad8-b4e4-cd625e9a23bd" src="https://github.com/QMUI/LookinServer/assets/39689377/d6004a8c-7e44-4349-8caa-31caf95e7d5f">

**Comment by hughkli** [comment]
iOS 17 的 API 问题，你可以先本地临时 return 掉，我今晚改一下发个 1.2.2 修一下

**Comment by hughkli** [comment]
@0xBa0 发了 1.2.2，你可以再试一下
