### ISSUE TITLE
在手机上无法使用2D模式

### ISSUE THREAD

**Issue by Hanpto** [QMUI/LookinServer#138]

**Comment by hughkli** [comment]
我刚刚试了一下，确实有这个问题，貌似是 UIWindow 的 makeKeyAndVisible API 在某个 iOS 版本之后就不管用了，需要 SceneDelegate 之类的东西，不懂。

不过我决定趁此机会直接移除 2D 和 3D 模式以降低维护成本，感觉用处不大，如果仍有人需要用类似功能，也许可以试试 FLEX 之类的其它 SDK。

**Comment by Hanpto** [comment]
您所发送的邮件已收到。
