### ISSUE TITLE
[bugfix] fix UIGraphicsBeginImageContext crash when you have a zero-size CALayer on iOS 17

### ISSUE THREAD

**Issue by GCSNNB** [QMUI/LookinServer#139]
看提交只是加了一个断言，崩溃的问题还是没有解决呀？

**Comment by hughkli** [comment]
有解决吧，你用的是最新的 1.2.3 版本吗？如果是 1.2.3 的话，可以把 Crash 的堆栈截个图看看吗？

**Comment by GCSNNB** [comment]
![截屏2023-11-09 08 05 54](https://github.com/QMUI/LookinServer/assets/45347880/bcb8c15f-f6af-42e1-b0a7-c5af7b27a2e2)
![截屏2023-11-09 08 09 16](https://github.com/QMUI/LookinServer/assets/45347880/77305ca6-9b72-450b-8a0f-09c15a3c1bc5)

**Comment by hughkli** [comment]
奇怪，理论上已经在上面做过保护了，算了我在下面再多补一个保护吧。
![image](https://github.com/QMUI/LookinServer/assets/15059475/6e222117-20f1-4f5b-9158-d9f6a0921b74)

或者也有可能 crash 的原因不是 size 为 0？下次再遇到可以看看 log 里具体报错是什么。

**Comment by hughkli** [comment]
刚刚发布的 1.2.4 LookinServer 里对此做了保护，可以先试试。仍然有问题的话，把堆栈和控制台里的报错信息都发一下。

**Comment by GCSNNB** [comment]
> 刚刚发布的 1.2.4 LookinServer 里对此做了保护，可以先试试。仍然有问题的话，把堆栈和控制台里的报错信息都发一下。

升级新版已经好了。👍

**Comment by GCSNNB** [comment]
还是有崩溃。
![截屏2023-11-13 15 49 06](https://github.com/QMUI/LookinServer/assets/45347880/eb3865d3-6de3-461b-a8f2-c6af9c7ac370)
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={1.7976931348623157e+308, 1.7976931348623157e+308}, scale=3.000000, bitmapInfo=0x2002. Use UIGraphicsImageRenderer to avoid this assert.'

**Comment by hughkli** [comment]
好家伙，原来是 size 太大了，我做个保护吧……

估计你的某个 view 的 frame 设置错误了，设置成了 inf 之类的，你也可以尝试规避一下。

**Comment by GCSNNB** [comment]
> 好家伙，原来是 size 太大了，我做个保护吧……
> 
> 估计你的某个 view 的 frame 设置错误了，设置成了 inf 之类的，你也可以尝试规避一下。

嗯嗯，昨天尝试找了下，没找到具体的view，12年的老代码了，坑太多。。。

**Comment by GCSNNB** [comment]
> 好家伙，原来是 size 太大了，我做个保护吧……
> 
> 估计你的某个 view 的 frame 设置错误了，设置成了 inf 之类的，你也可以尝试规避一下。

我昨天也尝试了下，把UIGraphicsBeginImageContext替换成UIGraphicsImageRenderer来实现。这个问题和size.w size.h为零，都不会崩溃。包括我们项目最低已经是iOS12+，所以把自己的代码中所有的UIGraphicsBeginImageContext都进行了替换。
在LookIn里面应该有三处用到了UIGraphicsBeginImageContext，如果考虑系统兼容iOS10-，可以参考SDWebImage的SDGraphicsImageRenderer这个类进行一层封装。大佬有时间可以看下～

**Comment by hughkli** [comment]
> 好家伙，原来是 size 太大了，我做个保护吧……
> 
> 估计你的某个 view 的 frame 设置错误了，设置成了 inf 之类的，你也可以尝试规避一下。

最新版 1.2.5 加了个保护
![screenshot-20231204-133207](https://github.com/QMUI/LookinServer/assets/15059475/b655610c-db4b-467d-ad16-7e25684459e9)
