### ISSUE TITLE
1.2.4 版本貌似未支持显示swift中xib的@IBOutlet var view成员变量名称

### ISSUE THREAD

**Issue by MrYu4** [QMUI/LookinServer#140]
另外感觉新版性能速度确实慢了很多，猜测是新功能的缘故

**Comment by MrYu4** [comment]
突然发现lookin右上角通知里面提示还有步骤没弄好，我先试着按照提示操作先 [如何为 Lookin 开启 Swift 优化](https://bytedance.larkoffice.com/docx/GFRLdzpeKoakeyxvwgCcZ5XdnTb)

**Comment by MrYu4** [comment]
> 突然发现lookin右上角通知里面提示还有步骤没弄好，我先试着按照提示操作先 [如何为 Lookin 开启 Swift 优化](https://bytedance.larkoffice.com/docx/GFRLdzpeKoakeyxvwgCcZ5XdnTb)

this works

**Comment by hughkli** [comment]
@MrYu4 具体是什么操作会卡呢？展开图层列表的时候卡一下？还是选中图层时会卡一下？
