### ISSUE TITLE
部分借鉴YourView的代码建议加上注释或者仓库首页加个参考链接。

### ISSUE THREAD

**Issue by SecondDog** [QMUI/LookinServer#143]
部分借鉴YourView的代码建议加上注释或者仓库首页加个参考链接。

**Comment by hughkli** [comment]
说的对，SceneKit 那里确实参考了 YourView 的，我之前处理不善，我尽快在仓库 Readme、代码文件、文档、软件界面等地方都补一下各种 credit。
