### ISSUE TITLE
查看 visionOS 的 App 时展示的设备名称是错误的

### ISSUE THREAD

**Issue by sunimp** [QMUI/LookinServer#144]
查看 visionOS 上的 App 的时候，macOS Lookin 展示的是 iPad (17.1)

<img src="https://github.com/QMUI/LookinServer/assets/16975429/191b6e96-835f-42fc-b379-07640c142025" alt="Image" width="500" height="556">

Lookin Server Version: 1.2.0
macOS Lookin Version: 1.0.5(12)

**Comment by hughkli** [comment]
因为你这个 App 并非原生 VisionOS App，而是 iPad 适配版吧，也就是所谓的“Designed for iPad”。
此时，你的 App 确实会对 Lookin 等第三方软件报告称自己是 iPad，这是符合预期的。


<img width="263" alt="截屏2024-03-10 23 56 25" src="https://github.com/QMUI/LookinServer/assets/15059475/1e7582c7-182d-46eb-88bf-62014eab2cdc">
<img width="479" alt="截屏2024-03-10 23 55 50" src="https://github.com/QMUI/LookinServer/assets/15059475/3ff15157-98c6-4396-b87b-71f2d10f0658">
