### ISSUE TITLE
1.0.0版本对UICollectionView的适配存在问题

### ISSUE THREAD

**Issue by donggelaile** [QMUI/LookinServer#15]
你好，问题是这样的：
1、mac lookin版本升级到1.0.0，客户端内部升级到最新framework后。查看UICollecitonView的页面时会干掉页面上的部分cell。(有的页面必现，有的页面正常)
2、lookin 0.9.3版本是正常的。
3、配上一张图片链接 https://tva1.sinaimg.cn/large/006y8mN6ly1g8ifasfw59g30p00ihwsi.gif

**Comment by hughkli** [comment]
奇怪，新版本应该没有相关逻辑的改动。

不知道是否方便把你这个 iOS 项目私发给我，我来看一下是哪里出了问题？

**Comment by donggelaile** [comment]
这是我的一个开源项目，https://github.com/donggelaile/HDCollectionView ，下载下来pod安装lookinServer再测试即可重现。
开始我以为跟我自定义系统layout有关，后来将demo2的hd_isUseSystemFlowLayout改为YES(改为YES就是使用系统flowlayout)也是出现。

**Comment by hughkli** [comment]
Lookin 刷新时，界面上的每一个 view 都必须被 Lookin 调用 setHidden、drawViewHierarchyInRect 等方法来绘制图像，而其中的某些调用似乎触发了你的某些业务逻辑，导致 HDCollectionCell.contentView 被添加了一些 AutoLayout 约束，而这些约束只设置了宽度没有设置高度，导致 HDCollectionCell.contentView 的高度可能被计算为 0，从而导致 cell 不见或无法点击。

但由于我不熟悉 AutoLayout，所以我没有找到这些非法约束是在你的项目里的哪里被添加的。

你可以在 Lookin 里刷新界面触发该 bug 后，打开 Xcode UI Inspector，然后会看到 HDCollectionCell 上的约束警告。
<img width="327" alt="屏幕快照 2019-11-01 14 15 42" src="https://user-images.githubusercontent.com/15059475/68009059-ca9ecf00-fcbb-11e9-95d8-c3860027e129.png">
<img width="263" alt="屏幕快照 2019-11-01 14 15 47" src="https://user-images.githubusercontent.com/15059475/68009060-cb376580-fcbb-11e9-9f9c-4fc797d6264f.png">

**Comment by donggelaile** [comment]
好的。可能是跟我的cell子view的frame缓存模式有些冲突，这个缓存是通过给一个tempCell来加约束实现的。感谢回答，回头我再研究一下。

**Comment by donggelaile** [comment]
1、研究了一下，发现最终触发加上这些layout的代码是父类cell的intrinsicContentSize方法。父类cell中实现了这个方法并添加了这些约束。
2、触发这个方法的确实是lookin点击刷新按钮后，附上一张函数调用栈。
![91D58A5E-E880-44B2-AC62-392E81F16E2C](https://user-images.githubusercontent.com/7498868/68095965-9c520700-fee8-11e9-9621-872c8194e744.png)
3、后期我考虑下是不是去掉这个父类的自定义实现，因为不是很有必要。。
