### ISSUE TITLE
能否支持显示颜色名字

### ISSUE THREAD

**Issue by TmFtZW9mR2l0aHVi** [QMUI/LookinServer#150]
既然已经支持了图片名字，这个能否做一样的处理
像xcode这样
<img width="360" alt="image" src="https://github.com/QMUI/LookinServer/assets/143387369/dcbdc1c6-ba1a-4a31-90ac-6e9a7cc08b7e">

**Comment by hughkli** [comment]
你是说截图里那个 primaryTitleColor 的字样吗？

Lookin 有个 API 可以让你自定义 UIColor 的名字，可以试一下：https://lookin.work/faq/config-file/ 
![image](https://github.com/QMUI/LookinServer/assets/15059475/e5700521-925e-404e-8ba0-1b4e8d9d64e4)
