### ISSUE TITLE
忽然无法使用了

### ISSUE THREAD

**Issue by fndppx** [QMUI/LookinServer#151]
<img width="523" alt="image" src="https://github.com/QMUI/LookinServer/assets/7971897/309a2111-5d3b-4668-80fe-71f0bd9d8ea7">
<img width="256" alt="image" src="https://github.com/QMUI/LookinServer/assets/7971897/cdd51001-0467-4740-aca5-6da2662e2437">

**Comment by miaozhang9** [comment]
老哥 解决了吗？我的也突然不能用了。

**Comment by fndppx** [comment]
> 老哥 解决了吗？我的也突然不能用了。

解决了，我是数据线坏了😂😂
