### ISSUE TITLE
通过`Swift Package Manager` 方式导入，使用问题

### ISSUE THREAD

**Issue by a51095** [QMUI/LookinServer#152]
- 通过`Swift Package Manager` 方式导入，
- 控制台没有 `Lookin`相关文字
- 有 `LKS_ConnectionManager.Swift` 文件, 即成功通过`Swift Package Manager`导入framework，但没有生效
- 工程结构比较复杂

我想在 `ReusableUITestApplication` 工程中引入使用 `lookin`

<img width="947" alt="iShot_2024-06-05_09 40 18" src="https://github.com/QMUI/LookinServer/assets/29021369/9d7d87d5-7e53-4be3-863e-1052cbc265e0">

**Comment by hughkli** [comment]
那说明 SHOULD_COMPILE_LOOKIN_SERVER 这个宏没有被正确置为 true
![image](https://github.com/QMUI/LookinServer/assets/15059475/909ded86-c5ba-4787-9b08-00e42019b785)
 
我试了一下全新的简单 Swift Demo 工程是没问题的，所以应该确实是你们的工程配置问题。
至于具体是什么问题……我没有什么经验（因为我个人工作都是使用 CocoaPods），可能需要你们自己排查一下。

**Comment by a51095** [comment]
感谢答复，操作错误，添加到指定target后，可以正常使用了，谢谢🤝🤝🤝
