### ISSUE TITLE
添加自定义属性后如何自动刷新Lookin？

### ISSUE THREAD

**Issue by rakuyoMo** [QMUI/LookinServer#154]
比如为`UIImageView`增加`contentMode`属性，在修改后视图发生了变化，但是 Lookin 里没有自动刷新，还维持着修改之后的样式。请问在修改后该如何触发刷新呢？

**Comment by hughkli** [comment]
没有“自动刷新 Lookin”的配置，因为这个有不少工作量，就懒得弄了。

可以在 Lookin 的右键菜单里，手动快速刷新某个图层的数据：
![image](https://github.com/QMUI/LookinServer/assets/15059475/02d49f69-913b-4df7-8e95-128059ea0ade)
