### ISSUE TITLE
无法通过lookin查看手机内容

### ISSUE THREAD

**Issue by InterFaceBino** [QMUI/LookinServer#155]
<img width="1039" alt="image" src="https://github.com/QMUI/LookinServer/assets/11565801/5d6e4479-c673-466a-b514-a469d058deee">
<img width="1121" alt="image" src="https://github.com/QMUI/LookinServer/assets/11565801/a1f4e0a3-b998-450a-9eb5-890e2cfcb159">

**Comment by hughkli** [comment]
通过文档自行排查一下？https://bytedance.larkoffice.com/docx/TvjvdfZsIoTszxxwPLsc29Rhneh

无法在 load 方法里断点的话，那可以在那行加一个 log，看看 log 会不会被打印出来？

**Comment by InterFaceBino** [comment]
排查过了，尝试log也无法打印
<img width="1383" alt="image" src="https://github.com/QMUI/LookinServer/assets/11565801/f16072f1-93e4-47b0-bd94-0f5f1c45401d">

**Comment by InterFaceBino** [comment]
解决了
<img width="1125" alt="image" src="https://github.com/QMUI/LookinServer/assets/11565801/744d1aaf-41ed-4f41-b55d-da4121cf6051">

**Comment by InterFaceBino** [comment]
pod setting 
to add path
