### ISSUE TITLE
关于自行创建xcconfig运行配置文件后，Lookin集成失败问题解决办法

### ISSUE THREAD

**Issue by Dongjian413** [QMUI/LookinServer#169]
pod 'LookinServer', :configurations => ['Debug']
如上是标准集成方式，因为Xcode默认提供【Debug】【Release】两种运行配置，如果你自行创建了xcconfig文件，这里 'Debug' 换为配置文件名称即可

**Comment by xyhuangjia** [comment]
> pod 'LookinServer', :configurations => ['Debug'] 如上是标准集成方式，因为Xcode默认提供【Debug】【Release】两种运行配置，如果你自行创建了xcconfig文件，这里 'Debug' 换为配置文件名称即可

用SPM 引入的有办法么？大佬
