### ISSUE TITLE
源码置入的时候找不到LKI_ConnectionManager.h文件

### ISSUE THREAD

**Issue by shengyang998** [QMUI/LookinServer#19]
还有一堆其他头文件，是不是不支持源码置入？

**Comment by hughkli** [comment]
本来就没有 LKI_ConnectionManager.h 这个文件。

支持源码导入的，这里是一些导入时的说明，看看能不能帮到你：https://lookin.work/faq/integration-sourcecode/

**Comment by shengyang998** [comment]
嗯是的，就是这个办法置入的framework，但是编译的时候发生了#import找不到头文件的情况
可以看看：
https://github.com/QMUI/LookinServer/search?q=LKI_ConnectionManager&unscoped_q=LKI_ConnectionManager
项目里面只有#import语句没有.h文件，这怎么编译得过呢？

亦或者是我遗漏了哪一步？

**Comment by hughkli** [comment]
没想到。。。这确实是我的问题，LKMConnectionManager.m 这个是不需要的废弃文件，这个文件的引用已经在 Lookin.xcodeproj 里被删掉了，但是并没有实际删掉这个文件，所以导致了你的报错。

我这就提交一下更新，删除 LKMConnectionManager.m 这个文件。

感谢反馈！
