### ISSUE TITLE
可以提供查看视图transform属性的功能吗

### ISSUE THREAD

**Issue by jiasongs** [QMUI/LookinServer#20]
做动画的时候比较有用

**Comment by hughkli** [comment]
现在确实没有直接查看 transform 的方法，以后的版本会考虑加上。

如果某些场景下急用，可以在右上角搜索框中搜索 transform，不过结果是一个矩阵，确实可读性比较低。

![WeWork Helper20191225142243](https://user-images.githubusercontent.com/15059475/71435016-0dac7a00-2722-11ea-9085-a2065df46e05.png)
