### ISSUE TITLE
not working with iOS 13

### ISSUE THREAD

**Issue by liu6x6** [QMUI/LookinServer#22]
hi 
look like lookin is not working with iOS 13. please check.
i think the problem could be : on iOS13 it need SSL for every connection

**Comment by hughkli** [comment]
Could you share more detailed error log, screenshot, or a demo project which can reproduce this error?

目前在其他用户的 iOS 13 上都正常运行没有问题，比如 Lookin 的 demo 项目（https://cdn.lookin.work/download/QMUI-Demo-1-0-0.zip），也许是你们的项目设置有一些特殊之处？可以提供更详细的报错信息、截屏吗？或者给一个能重现该问题的 demo 项目是最好的。

**Comment by liu6x6** [comment]
i test again and it's working.
