### ISSUE TITLE
在手机上无法使用

### ISSUE THREAD

**Issue by zhangjianbin** [QMUI/LookinServer#24]
工程已经pod 'LookinServer', :configurations => ['Debug']的前提下，发送[[NSNotificationCenter defaultCenter] postNotificationName:@"Lookin_3D" object:nil];控制台提示LookinServer - Connected successfully on 127.0.0.1:47164，但是手机上仅仅显示个toast，toast消失太快仅仅能看到个make 8。。。。手机系统是iOS13，xcode11.

**Comment by chimingzi** [comment]
我这边是iOS13上面不能调出。iOS12.x上暂时没发现什么问题。

**Comment by nanshanyi** [comment]
我也遇到同样问题，如下解决方式
iOS 13之后如果使用了SceneDelegate，那keyWindow用原来的方法是无法更改的
        self.contentWindow.hidden = NO;
        [self.contentWindow makeKeyAndVisible];
也就是这段代码无效
需要更改LKS_PerspectiveManager中的window才能弹出
可以删除 self.contentWindow = [LKS_PerspectiveContainerWindow new];
增加如下方法即可
- (LKS_PerspectiveContainerWindow *)contentWindow{
    if (!_contentWindow) {
        if (@available(iOS 13.0, *)) {
            UIWindowScene * windowScene = (UIWindowScene *)UIApplication.sharedApplication.connectedScenes.allObjects.firstObject;
            _contentWindow = (LKS_PerspectiveContainerWindow *)[[UIWindow alloc] initWithWindowScene:windowScene];
        } else {
            _contentWindow = [LKS_PerspectiveContainerWindow new];
        };
    }
    return _contentWindow;
}

**Comment by hughkli** [comment]
> 我也遇到同样问题，如下解决方式
> iOS 13之后如果使用了SceneDelegate，那keyWindow用原来的方法是无法更改的
> self.contentWindow.hidden = NO;
> [self.contentWindow makeKeyAndVisible];
> 也就是这段代码无效
> 需要更改LKS_PerspectiveManager中的window才能弹出
> 可以删除 self.contentWindow = [LKS_PerspectiveContainerWindow new];
> 增加如下方法即可
> 
> * (LKS_PerspectiveContainerWindow *)contentWindow{
>   if (!_contentWindow) {
>   if (@available(iOS 13.0, *)) {
>   UIWindowScene * windowScene = (UIWindowScene *)UIApplication.sharedApplication.connectedScenes.allObjects.firstObject;
>   _contentWindow = (LKS_PerspectiveContainerWindow *)[[UIWindow alloc] initWithWindowScene:windowScene];
>   } else {
>   _contentWindow = [LKS_PerspectiveContainerWindow new];
>   };
>   }
>   return _contentWindow;
>   }

原来如此，感谢提出
