### ISSUE TITLE
在哪里可以查看视图MidX/MidY、MaxX/MaxY的数值？

### ISSUE THREAD

**Issue by devcxm** [QMUI/LookinServer#26]
记得最初的版本好像是可以查看这些值的，现在砍掉了吗？感觉这4个值对开发非常有用，能否考虑在下个版本加上视图的这些值？

**Comment by hughkli** [comment]
对，砍掉了。
看看能不能用顶部工具栏里的“测距”功能实现你的需求？



&nbsp;


------------------ 原始邮件 ------------------
发件人: Xiaoming <notifications@github.com&gt;
发送时间: 2020年4月21日 09:08
收件人: QMUI/LookinServer <LookinServer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[QMUI/LookinServer] 在哪里可以查看视图MidX/MidY、MaxX/MaxY的数值？ (#26)





 
记得最初的版本好像是可以查看这些值的，现在砍掉了吗？感觉这4个值对开发非常有用，能否考虑在下个版本加上视图的这些值？

**Comment by devcxm** [comment]
@hughkli 不知道为什么要砍掉这个功能，如果可以的话，还是期望把这些功能加回去。要是这些数值太占侧边栏，可以在现有交互方式自定义添加/删除这些数值的显示。

**Comment by hughkli** [comment]
你说的确实有道理，我们下个版本把这个功能重新加回去。



&nbsp;


------------------ 原始邮件 ------------------
发件人: Xiaoming <notifications@github.com&gt;
发送时间: 2020年4月21日 11:13
收件人: QMUI/LookinServer <LookinServer@noreply.github.com&gt;
抄送: Li Kai <hughfrakes@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[QMUI/LookinServer] 在哪里可以查看视图MidX/MidY、MaxX/MaxY的数值？ (#26)






@hughkli 不知道为什么要砍掉这个功能，如果可以的话，还是期望把这些功能加回去。要是这些数值太占侧边栏，可以在现有交互方式自定义添加/删除这些数值的显示。
