### ISSUE TITLE
使用了不错，有个疑问，基础这个提交AppStore会有影响吗？我之前基础Realve就存在提价不上的问题

### ISSUE THREAD

**Issue by WCMYCML** [QMUI/LookinServer#27]
提交AppStore是否有影响，提交时是否需要移除呢

**Comment by hughkli** [comment]
提交时需要移除的，否则用户也可以连接 Lookin 修改你的 app 了。


不过更方便的做法应该是引入 framework 时设置为“仅在 Debug 模式下引入”，无需在提交的时候手动移除。

&nbsp;


------------------ 原始邮件 ------------------
发件人: 云残 <notifications@github.com&gt;
发送时间: 2020年4月29日 11:54
收件人: QMUI/LookinServer <LookinServer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[QMUI/LookinServer] 使用了不错，有个疑问，基础这个提交AppStore会有影响吗？我之前基础Realve就存在提价不上的问题 (#27)





 
提交AppStore是否有影响，提交时是否需要移除呢
