### ISSUE TITLE
查看手势功能被砍了吗？

### ISSUE THREAD

**Issue by songhongkang** [QMUI/LookinServer#28]

**Comment by hughkli** [comment]
没有啊，自从上了这个功能后这软件就再也没有更新过了



&nbsp;


------------------ 原始邮件 ------------------
发件人: songhongkang <notifications@github.com&gt;
发送时间: 2020年5月22日 18:03
收件人: QMUI/LookinServer <LookinServer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[QMUI/LookinServer] 查看手势功能被砍了吗？ (#28)

**Comment by songhongkang** [comment]
找到了。
