### ISSUE TITLE
有考虑支持Flutter么？

### ISSUE THREAD

**Issue by qq432591** [QMUI/LookinServer#31]

**Comment by hughkli** [comment]
你好，暂时没有这个计划



&nbsp;


------------------ 原始邮件 ------------------
发件人: Jiandan <notifications@github.com&gt;
发送时间: 2020年9月17日 00:31
收件人: QMUI/LookinServer <LookinServer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[QMUI/LookinServer] 有考虑支持Flutter么？ (#31)
