### ISSUE TITLE
Xcode12 模拟器

### ISSUE THREAD

**Issue by shuiliang** [QMUI/LookinServer#32]
Xcode12 ，Lookin 里的3D模式看不到模拟器界面

<img width="744" alt="iShot2020-09-17 16 27 10" src="https://user-images.githubusercontent.com/17922774/93442930-bb8c3400-f902-11ea-9a72-7ecc026689b3.png">

**Comment by hughkli** [comment]
奇怪，我这边重现不了，你那边可以提供一个能重现该问题的 demo 项目吗

**Comment by HasjOH** [comment]
同样的问题，切到2D才可以

**Comment by HasjOH** [comment]
同样的问题，切到2D才可以

使用的是 CocoaPods导入库的方式

**Comment by ykRyanan** [comment]
解决了吗 更新Xcode12后 同3D不显示

**Comment by shuiliang** [comment]
我当时是xcode11 和xcode12 共存的，后来我两个都删了，重新安装xcode12后发现能正常使用了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QMUI/LookinServer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 晚上6:19
收件人:&nbsp;"QMUI/LookinServer"<LookinServer@noreply.github.com&gt;;
抄送:&nbsp;"水亮Real"<1025838111@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [QMUI/LookinServer] Xcode12 模拟器 (#32)





 
解决了吗 更新Xcode12后 同3D不显示

**Comment by JoyaWang** [comment]
我也出现了这个问题，但是间歇性的，有的时候会有，我已经发邮件给lookin@lookin.work了
![3D不显示图层](https://user-images.githubusercontent.com/13715852/97515087-3600a700-19cb-11eb-9711-170ac6f08967.gif)

**Comment by JoyaWang** [comment]
现在完全不显示了，Xcodehui会有这样的输出
![Snip20201029_2](https://user-images.githubusercontent.com/13715852/97515271-adced180-19cb-11eb-85d8-ebbd5f144dc0.png)

**Comment by JoyaWang** [comment]
把CG_CONTEXT_SHOW_BACKTRACE 设为1以后，每次在Lookin中一点击刷新，Xcode会出现下面的输出
<img width="930" alt="截屏2020-10-29 09 58 58" src="https://user-images.githubusercontent.com/13715852/97516168-81b45000-19cd-11eb-822f-6e43cc93e1e6.png">
<img width="931" alt="截屏2020-10-29 09 59 15" src="https://user-images.githubusercontent.com/13715852/97516176-87aa3100-19cd-11eb-96ad-6dec9bc6ca1e.png">
<img width="929" alt="截屏2020-10-29 09 59 31" src="https://user-images.githubusercontent.com/13715852/97516188-8c6ee500-19cd-11eb-8e2e-fb048ec8ae8b.png">
<img width="924" alt="截屏2020-10-29 09 59 42" src="https://user-images.githubusercontent.com/13715852/97516195-90026c00-19cd-11eb-8711-ee6d83b44570.png">

**Comment by JoyaWang** [comment]
发现真机是没问题的
