### ISSUE TITLE
LookinConnectionAttachment

### ISSUE THREAD

**Issue by azureplus** [QMUI/LookinServer#33]
-[LookinConnectionAttachment objectForKeyedSubscript:]: unrecognized selector sent to instance 0x2811cbd60

**Comment by hughkli** [comment]
之前一直正常使用，然后今天突然出现了这个错误？



&nbsp;


------------------ Original ------------------

**Comment by azureplus** [comment]
> 之前一直正常使用，然后今天突然出现了这个错误？ &nbsp;
> […](#)

越狱设备上调试就会出现这个奔溃

**Comment by hughkli** [comment]
现在的信息有点少不太能猜出来bug原因，不知道能不能看到那个“unrecognized selector”的 selector 名字是啥

**Comment by Channe** [comment]
需要在越狱手机 lookin 插件中关闭debug APP

**Comment by shibinSun** [comment]
'-[LookinConnectionAttachment objectForKeyedSubscript:]: unrecognized selector sent to instance 0x280fe7900' 
我是lookin添加方法监听之后。在打开lookin就会崩溃

**Comment by kingnight** [comment]
> 需要在越狱手机 lookin 插件中关闭debug APP

测试有效
