### ISSUE TITLE
3D 视图空白，2D 可展示。

### ISSUE THREAD

**Issue by uclort** [QMUI/LookinServer#34]
常常碰到这种情况。

**Comment by nlnlnull** [comment]
常常碰到这种情况。

**Comment by Vanson** [comment]
+1

**Comment by xixisplit** [comment]
+1.我的一个项目也遇到了这个情况.首页也出现了3D 空白

**Comment by xixisplit** [comment]
> +1.我的一个项目也遇到了这个情况.首页也出现了3D 空白

我这边排查之后是因为 SDCycleScrollView 控件的参数currentPageDotImage 和 pageDotImage 未设置导致的.将对应参数设置为 UIImage.new 就 ok 了.可能是因为这个控件内部的一些操作导致lookin 在 运作的时候.出现了一些意外

**Comment by LinXunFeng** [comment]
## 问题
3D和2D都空白

该问题只存在于一个页面，其它页面都可正常调试

## 原因
我这边经排查，是因为使用了`SDWebImageLottiePlugin`，只要页面上创建出来的`LOTAnimationView`对象在加载动图文件时就会出现这种情况，其它没有使用`LOTAnimationView`的页面，`Lookin`则可正常使用

**Comment by uclort** [comment]
@hughkli 大佬，这个问题请问你们团队有碰到过么？有安排解决了么？

**Comment by hughkli** [comment]
没有碰到过。
因为业务太忙了所以暂时没有时间维护这个项目，只能期望今年找个时间能改改吧……

&nbsp;


------------------ 原始邮件 ------------------
发件人: null ***@***.***&gt;
发送时间: 2021年5月11日 14:01
收件人: QMUI/LookinServer ***@***.***&gt;
抄送: Li Kai ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[QMUI/LookinServer] 3D 视图空白，2D 可展示。 (#34)





 
@hughkli 大佬，这个问题请问你们团队有碰到过么？有安排解决了么？

**Comment by uclort** [comment]
@hughkli 写了个能复现的`Demo`，在我这具体表现为自定义一个控件，重写控件的`layoutSubviews`，然后在`layoutSubviews`方法中改变控件的`frame`，如果尺寸相差过大就会空白。
初始化控件的时候`frame` 设置为 `.init(x: 20, y: 50, width: 200, height: 20)`
然后在`layoutSubviews`方法中进行计算后把`frame`修改为`.init(x: 20, y: 50, width: 10, height: 20)`，就会白屏。

## Demo👇🏻
[Lookin_3D_Demo.zip](https://github.com/QMUI/LookinServer/files/6457581/Lookin_3D_Demo.zip)

**Comment by hughkli** [comment]
刚刚看了 @uclort 给的可以重现该 bug 的 demo，发现原因是：某些 UIView 的 frame 不合法（比如出现了 NaN 或者 Inf 之类的）导致 Lookin 的 3D 图像渲染错误。

我刚刚在 CocoaPods 发布了 LookinServer 1.0.4，内容是读取 frame 时过滤掉不合法的值，亲测可以解决 @uclort 给出的 Demo。

但不确定是否可以解决其他人的 bug，如果不能解决，请继续在该 issue 下告诉我。
