### ISSUE TITLE
m1 mac 编译不了模拟器包, 会提示找不到arm64架构

### ISSUE THREAD

**Issue by miku1958** [QMUI/LookinServer#35]

**Comment by daiweilai** [comment]
@miku1958  自己使用源码重新编译出LookinServer.framework 然后拖进项目中就可以了

**Comment by hughkli** [comment]
@miku1958 最近几天发布的 1.0.2 版本的 LookinServer 已经支持 M1 了，可以试下：https://cocoapods.org/pods/LookinServer
