### ISSUE TITLE
Xcode 12.2 crash

### ISSUE THREAD

**Issue by ruby109** [QMUI/LookinServer#36]
2020-12-07 16:09:41.239555+0800 ******[1678:318076] [Bugly]  Trapped uncaught exception 'NSInvalidArgumentException', reason: 'Passing argument that is not a CGColor to +[UIColor colorWithCGColor:]' 
(
	0   CoreFoundation                      0x00000001861e25c0 472C9193-115D-34CD-AD1D-0E7E091C9432 + 1185216
	1   libobjc.A.dylib                     0x000000019a25c42c objc_exception_throw + 60
	2   CoreFoundation                      0x00000001860dea9c 472C9193-115D-34CD-AD1D-0E7E091C9432 + 121500
	3   UIKitCore                           0x000000018869ba78 47154C6D-47DF-3ABB-A152-56B159B014E4 + 7457400
	4   CoreFoundation                      0x00000001861e75d4 472C9193-115D-34CD-AD1D-0E7E091C9432 + 1205716
	5   CoreFoundation                      0x00000001860c29e8 472C9193-115D-34CD-AD1D-0E7E091C9432 + 6632
	6   LookinServer                        0x00000001075be0a4 +[LKS_AttrGroupsMaker _attributeWithIdentifer:targetObject:] + 344
	7   LookinServer                        0x00000001075bdeb0 __42+[LKS_AttrGroupsMaker attrGroupsForLayer:]_block_invoke_3 + 340
	8   LookinServer                        0x00000001075ce8dc __30-[NSArray(Lookin) lookin_map:]_block_invoke + 40
	9   CoreFoundation                      0x0000000186163038 472C9193-115D-34CD-AD1D-0E7E091C9432 + 663608
	10  CoreFoundation                      0x00000001860c306c 472C9193-115D-34CD-AD1D-0E7E091C9432 + 8300
	11  LookinServer                        0x00000001075ce860 -[NSArray(Lookin) lookin_map:] + 188
	12  LookinServer                        0x00000001075bdcb8 __42+[LKS_AttrGroupsMaker attrGroupsForLayer:]_block_invoke_2 + 208
	13  LookinServer                        0x00000001075ce8dc __30-[NSArray(Lookin) lookin_map:]_block_invoke + 40
	14  CoreFoundation                      0x0000000186163038 472C9193-115D-34CD-AD1D-0E7E091C9432 + 663608
	15  CoreFoundation                      0x00000001860c306c 472C9193-115D-34CD-AD1D-0E7E091C9432 + 8300
	16  LookinServer                        0x00000001075ce860 -[NSArray(Lookin) lookin_map:] + 188
	17  LookinServer                        0x00000001075bdad4 __42+[LKS_AttrGroupsMaker attrGroupsForLayer:]_block_invoke + 208
	18  LookinServer                        0x00000001075ce8dc __30-[NSArray(Lookin) lookin_map:]_block_invoke + 40
	19  CoreFoundation                      0x0000000186163038 472C9193-115D-34CD-AD1D-0E7E091C9432 + 663608
	20  CoreFoundation                      0x00000001860c306c 472C9193-115D-34CD-AD1D-0E7E091C9432 + 8300
	21  LookinServer                        0x00000001075ce860 -[NSArray(Lookin) lookin_map:] + 188
	22  LookinServer                        0x00000001075bd9c0 +[LKS_AttrGroupsMaker attrGroupsForLayer:] + 148
	23  LookinServer                        0x00000001075c0d8c __55-[LKS_HierarchyDetailsHandler _dequeueAndHandlePackage]_block_invoke_2 + 504
	24  LookinServer                        0x00000001075ce8dc __30-[NSArray(Lookin) lookin_map:]_block_invoke + 40
	25  CoreFoundation                      0x0000000186163038 472C9193-115D-34CD-AD1D-0E7E091C9432 + 663608
	26  CoreFoundation                      0x00000001860c306c 472C9193-115D-34CD-AD1D-0E7E091C9432 + 8300
	27  LookinServer                        0x00000001075ce860 -[NSArray(Lookin) lookin_map:] + 188
	28  LookinServer                        0x00000001075c0ae4 __55-[LKS_HierarchyDetailsHandler _dequeueAndHandlePackage]_block_invoke + 192
	29  libdispatch.dylib                   0x00000001079b3b68 _dispatch_call_block_and_release + 32
	30  libdispatch.dylib                   0x00000001079b55f0 _dispatch_client_callout + 20
	31  libdispatch.dylib                   0x00000001079c4890 _dispatch_main_queue_callback_4CF + 1000
	32  CoreFoundation                      0x000000018615f1e4 472C9193-115D-34CD-AD1D-0E7E091C9432 + 647652
	33  CoreFoundation                      0x00000001861593b4 472C9193-115D-34CD-AD1D-0E7E091C9432 + 623540
	34  CoreFoundation                      0x00000001861584bc CFRunLoopRunSpecific + 600
	35  GraphicsServices                    0x000000019cbdd820 GSEventRunModal + 164
	36  UIKitCore                           0x0000000188afc734 47154C6D-47DF-3ABB-A152-56B159B014E4 + 12048180
	37  UIKitCore                           0x0000000188b01e10 UIApplicationMain + 168
	38  ******                           0x0000000103539ee8 main + 88
	39  libdyld.dylib                       0x0000000185e1fe60 90A4E82E-250C-35E3-8B2D-51D6D8B1119B + 3680
)

**Comment by ruby109** [comment]
应该是因为在 Xib 中使用 Runtime Attributes 设置了 borderColor 导致的，能想办法兼容一下吗？

**Comment by hughkli** [comment]
好的，我研究一下这个，争取在后续版本里修复它



&nbsp;


------------------ Original ------------------

**Comment by Folobe26** [comment]
I think this problem should not be covered by Lookin, and maybe you are using a wrong way to set `layer.borderColor` in xib with a UIColor.

**Comment by ivoidcat** [comment]
同样遇到了

**Comment by ivoidcat** [comment]
加了个trycarch暂时解决了

**Comment by hughkli** [comment]
最新版已经加上了相关类型校验，应该不会 crash 了
