### ISSUE TITLE
我想查看任意其它app. 越狱机上怎么搞？有没有插件可以安装像reveal一样的吗？

### ISSUE THREAD

**Issue by feifeiwuxian** [QMUI/LookinServer#4]

**Comment by hughkli** [comment]
可以在 github 上搜索 “LookinLoader”  


------------------ 原始邮件 ------------------
发件人: feifeiwuxian <notifications@github.com>
发送时间: 2019年8月23日 09:32
收件人: QMUI/LookinServer <LookinServer@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[QMUI/LookinServer] 我想查看任意其它app. 越狱机上怎么搞？有没有插件可以安装像reveal一样的吗？ (#4)

**Comment by creantan** [comment]
可以使用我写的LookinLoader，自己编译或者直接下载deb包安装都可以，使用方法同RevealLoader一样。
https://github.com/creantan/LookinLoader
