### ISSUE TITLE
Show accessibilityIdentifier for a UIView 

### ISSUE THREAD

**Issue by Folobe26** [QMUI/LookinServer#40]
As `accessibilityIdentifier` is one of the most important property for automated UI Test, it does help a lot if this property can be showed in the right panel directly.

As app on macOS is not open-source for now, if this enhancement can be adopted, to reduce you guys work, I'm very glad to contribute the part of `LookinServer`.

Thanks.

**Comment by hughkli** [comment]
The latest version now supports custom attribute display.
