### ISSUE TITLE
“Lookin_Export“怎么把文件缓存到本地

### ISSUE THREAD

**Issue by zhongjianfeipqy** [QMUI/LookinServer#43]
不通过分享的方式，如何获取这个lookin文件呢

**Comment by hughkli** [comment]
应该是没有别的办法的，无法保存到本地，这样确实不好，以后改改



&nbsp;


------------------ 原始邮件 ------------------
发件人: Fly ***@***.***&gt;
发送时间: 2021年3月15日 17:50
收件人: QMUI/LookinServer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[QMUI/LookinServer] “Lookin_Export“怎么把文件缓存到本地 (#43)





 
不通过分享的方式，如何获取这个lookin文件呢
