### ISSUE TITLE
现在支持M1芯片么 ？

### ISSUE THREAD

**Issue by hongzengyang** [QMUI/LookinServer#46]
我现在使用的是M1芯片的Mac，无法使用。现在是否支持了M1芯片呢

**Comment by hughkli** [comment]
不支持，但是似乎 @ziecho 通过这个 github 里的文件自己手动打了一个支持 M1 的 framework，惊为天人

**Comment by hughkli** [comment]
@hongzengyang 前几天发布的 1.0.2 版本的 LookinServer 已经支持 M1 了：https://cocoapods.org/pods/LookinServer
