### ISSUE TITLE
Mac客户端必须10.14+

### ISSUE THREAD

**Issue by Codelem** [QMUI/LookinServer#5]
Mac客户端必须10.14+,有什么特殊理由吗

**Comment by hughkli** [comment]
因为身边找不到 10.14 之前的机器不好测试，以及觉得 iOS 开发者们的机器应该都是更新比较及时的，就做了这样的设定，从而方便使用最新的 macOS API、减少一些兼容性代码的编写

**Comment by Codelem** [comment]
是否可以编译出一个10.13系统的版本，因为某些原因设备无法及时升级。如果有兼容性有困难的话就忽略本回复

**Comment by hughkli** [comment]
好的，理解，我们会在下个版本更新里支持 10.13

（不过下个版本更新可能比较久，也许两周或三周或四周之后。。）
