### ISSUE TITLE
控制台带参数的方法调用会支持吗？

### ISSUE THREAD

**Issue by Jason-an** [QMUI/LookinServer#51]
控制台带参数的方法调用会支持吗？

**Comment by hughkli** [comment]
不会支持，下个版本甚至会取消掉控制台这个作用不大的功能，从而降低维护成本。

&nbsp;


------------------ 原始邮件 ------------------
发件人: Jason-an ***@***.***&gt;
发送时间: 2021年5月31日 09:56
收件人: QMUI/LookinServer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[QMUI/LookinServer] 控制台带参数的方法调用会支持吗？ (#51)





 
控制台带参数的方法调用会支持吗？
