### ISSUE TITLE
Preview window is blank.

### ISSUE THREAD

**Issue by modar-k** [QMUI/LookinServer#54]
I’m using Lookin on macOS Catalina with an iOS 14 device. The preview (middle) window inside Lookin app seems to be blank. However, when I hover over that window, different elements in the side (left) bar are highlighted which I suppose means the preview is there, but for some reason not showing.

**Comment by hughkli** [comment]
After turning the preview from 3D to 2D, is the preview image still blank?

&nbsp;


------------------ Original ------------------
From: modar-k ***@***.***&gt;
Date: Fri,Jun 18,2021 0:25 AM
To: QMUI/LookinServer ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [QMUI/LookinServer] Preview window is blank. (#54)





 
I’m using Lookin on macOS Catalina with an iOS 14 device. The preview (middle) window inside Lookin app seems to be blank. However, when I hover over that window, different elements in the side (left) bar are highlighted which I suppose means the preview is there, but for some reason not showing.

**Comment by modar-k** [comment]
> After turning the preview from 3D to 2D, is the preview image still blank? &nbsp;
> […](#)

Yes, unfortunately.
I tried to use Lookin with both the demo app, and a 3rd party app suing LookinLoader on a jailbroken iPhone.. same result.

**Comment by hughkli** [comment]
You mean you can reproduce this bug even with the demo app? It seems like a bug I’ve never heard before, and I can’t figure out possible reason for the moment.&nbsp;
Is this the first time you use Lookin on your computer?&nbsp;

&nbsp;


------------------ Original ------------------
From: modar-k ***@***.***&gt;
Date: Fri,Jun 18,2021 0:46 AM
To: QMUI/LookinServer ***@***.***&gt;
Cc: Li Kai ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [QMUI/LookinServer] Preview window is blank. (#54)





  
After turning the preview from 3D to 2D, is the preview image still blank? &nbsp;
 …
  
Yes, unfortunately.
 I tried to use Lookin with both the demo app, and a 3rd party app suing LookinLoader on a jailbroken iPhone.. same result.

**Comment by modar-k** [comment]
Yes, it’s my first time using it. After encountering this issue I decided to give “Reveal” a try. Surprisingly, I had the same issue in Reveal!

I guess then the problem could be iPhone/macOS related.

**Comment by jiemi** [comment]
I have the same problem.When I switched 2D to 3D or 3D to 2D,the preview was  shown for a moment about 0.2second and  disappeared later soon.  
When I clicked the reload button, I saw the log below
"[Unknown process name] CGAffineTransformInvert: singular matrix."

**Comment by lxxxzzz** [comment]
I have the same problem
