### ISSUE TITLE
发生了同样的问题,有没有解决办法,开始时候可以使用,没动哪里,突然就崩溃在了// 这个 ivarObject 可能的类型：UIView, CALayer, UIViewController, UIGestureRecognizer         NSObject *ivarObject = object_getIvar(hostObject, ivar);这里

### ISSUE THREAD

**Issue by runcong1989** [QMUI/LookinServer#55]
![截屏2020-06-11 上午10 54 56](https://user-images.githubusercontent.com/8233271/84339954-24606380-abd2-11ea-8f4f-06b991d86120.png)
![企业微信截图_420370f1-f055-4ee5-b08b-21d1e82b736f](https://user-images.githubusercontent.com/8233271/84336965-0e02d980-abcb-11ea-81ac-3fc8e7c10906.png)
![截屏2020-06-11 上午10 02 51](https://user-images.githubusercontent.com/8233271/84336985-1ce98c00-abcb-11ea-9445-3ff3b8410132.png)

_Originally posted by @Jinlongning in https://github.com/QMUI/LookinServer/issues/29#issuecomment-642361553_

**Comment by theskyQQ** [comment]
可以试试1.0.0版本 我之前用1.0.0没问题 换成1.0.2就崩溃 然后回退就好了

**Comment by runcong1989** [comment]
感谢，我试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: thesky ***@***.***&gt;
发送时间: 2021年6月25日 09:42
收件人: QMUI/LookinServer ***@***.***&gt;
抄送: runcong ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[QMUI/LookinServer] 发生了同样的问题,有没有解决办法,开始时候可以使用,没动哪里,突然就崩溃在了// 这个 ivarObject 可能的类型：UIView, CALayer, UIViewController, UIGestureRecognizer         NSObject *ivarObject = object_getIvar(hostObject, ivar);这里 (#55)





 
可以试试1.0.0版本 我之前用1.0.0没问题 换成1.0.2就崩溃 然后回退就好了
