### ISSUE TITLE
建议一个小功能

### ISSUE THREAD

**Issue by harryzjm** [QMUI/LookinServer#56]
首先整体很棒
在复杂的界面时 显示错综复杂 
希望能 focus 一个 view 或 layer 展示从这个 控件 开始的 结构
现在 始终都是从 UIWindowLayer 开始 层级太多

**Comment by hughkli** [comment]
这个确实是很多人都提到的一个问题，未来版本一定会改



&nbsp;


------------------ 原始邮件 ------------------
发件人: Hares ***@***.***&gt;
发送时间: 2021年6月25日 18:01
收件人: QMUI/LookinServer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[QMUI/LookinServer] 建议一个小功能 (#56)





 
首先整体很棒
 在复杂的界面时 显示错综复杂
 希望能 focus 一个 view 或 layer 展示从这个 控件 开始的 结构
 现在 始终都是从 UIWindowLayer 开始 层级太多
