### ISSUE TITLE
Any plans to support tvOS?

### ISSUE THREAD

**Issue by m4p** [QMUI/LookinServer#58]

**Comment by hughkli** [comment]
Sorry. As a side project with very limited developing time, I don’t have any plans to support tvOS.

&nbsp;


------------------ Original ------------------
From: Martin Pittenauer ***@***.***&gt;
Date: Tue,Jun 29,2021 6:07 PM
To: QMUI/LookinServer ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [QMUI/LookinServer] Any plans to support tvOS? (#58)

**Comment by m4p** [comment]
See #59 ;)

**Comment by hughkli** [comment]
Wow, it's amazing. I'll handle [#59](https://github.com/QMUI/LookinServer/pull/59/commits/5930550117287e8aa0a6c04a9ed927c07044c098) in the next several days as soon as possible.

**Comment by hughkli** [comment]
I just drafted a new release '1.0.3' to support tvOS. You can update your cocoapod or spm.
