### ISSUE TITLE
很nice，提点建议

### ISSUE THREAD

**Issue by donggelaile** [QMUI/LookinServer#6]
比系统的要快，手机端查看很不错。提两个小建议：
1、希望可以支持UITableView的sectionHeader及sectionFooter的标示和段数，目前好像只支持UICollectionView。
2、手机端2D模式点击UIImageView可以查看图片的imageName。电脑端好像不支持这个功能啊。

**Comment by hughkli** [comment]
> 比系统的要快，手机端查看很不错。提两个小建议：
> 1、希望可以支持UITableView的sectionHeader及sectionFooter的标示和段数，目前好像只支持UICollectionView。
> 2、手机端2D模式点击UIImageView可以查看图片的imageName。电脑端好像不支持这个功能啊。

感谢反馈，我们会在下个版本加上这两个功能
