### ISSUE TITLE
SPM Support?

### ISSUE THREAD

**Issue by yeguizhong** [QMUI/LookinServer#60]

**Comment by hughkli** [comment]
YES.

Repository: "https://github.com/QMUI/LookinServer", Rules: Version: 1.0.2

**Comment by Archer353** [comment]
> YES.
> 
> Repository: "https://github.com/QMUI/LookinServer", Rules: Version: 1.0.2

我用spm下载了，然后target的framework也添加了，运行时，日志里没有打印与LookIn相关的东西，也连接不上iPhone的APP，请问我该怎么设置？

**Comment by hughkli** [comment]
在 LKS_ConnectionManager.m 文件里的下面这个 load 方法里打断点，然后启动 iOS App，看看是否可以走到断点里？
![screenshot-20220926-214645](https://user-images.githubusercontent.com/15059475/192293253-f263cf05-8a11-49be-8e8b-0df75e9ad7c3.png)
