### ISSUE TITLE
xcode 12.5 lookin不能显示控制器名称了

### ISSUE THREAD

**Issue by heyehao2008** [QMUI/LookinServer#61]
之前挺好用的，xcode升级后，不显示控制器名称了
![截屏2021-07-29 下午5 00 14](https://user-images.githubusercontent.com/7590049/127463644-092f55f2-484c-476a-8c34-638c7d129dde.png)

**Comment by hughkli** [comment]
我这边用 12.5 的 XCode 没能重现你的问题，你可以尝试两种方法：
1）发给我一个能重现该 bug 的 demo iOS 项目
2）你在 UIViewController+LookinServer.m 文件的 lks_viewDidLoad 方法里打个断点，然后重新运行你的 iOS 项目，看看是否可以正常走进这个断点里面

**Comment by heyehao2008** [comment]
> 我这边用 12.5 的 XCode 没能重现你的问题，你可以尝试两种方法：
> 1）发给我一个能重现该 bug 的 demo iOS 项目
> 2）你在 UIViewController+LookinServer.m 文件的 lks_viewDidLoad 方法里打个断点，然后重新运行你的 iOS 项目，看看是否可以正常走进这个断点里面

排查了一下，是项目从某个版本开始出现的，之前的版本跑起来都是正常的。应该是项目中引入的某写东西造成的，我再排查一下

**Comment by heyehao2008** [comment]
> 我这边用 12.5 的 XCode 没能重现你的问题，你可以尝试两种方法：
> 1）发给我一个能重现该 bug 的 demo iOS 项目
> 2）你在 UIViewController+LookinServer.m 文件的 lks_viewDidLoad 方法里打个断点，然后重新运行你的 iOS 项目，看看是否可以正常走进这个断点里面

已经找到问题，是引入的一个三方SDK，方法交换有问题，导致其他的方法交换不调用。lks_viewDidLoad没走，现已解决。
感谢提供如此方便的工具！
