### ISSUE TITLE
纯Swift项目，Swift的类添加了控件，并不能在LookinServer里显示控件属性名

### ISSUE THREAD

**Issue by 0xBowen** [QMUI/LookinServer#62]
如题

Xcode版本：12.5.1
运行设备：iPhone XS max
LookinServer版本：1.0.3

<img width="610" alt="image" src="https://user-images.githubusercontent.com/39689377/127822911-af61c332-b66b-434d-bd90-23bfe20194a3.png">

![image](https://user-images.githubusercontent.com/39689377/127823087-a8bcf070-2984-4a83-b1cb-1a38207c65a0.png)

**Comment by hughkli** [comment]
这是符合预期的。

“显示属性名”目前不支持 Swift 相关的类，原因是无法通过 class_copyIvarList 相关方法拿到一个 Swift 类的属性对象（具体业务逻辑：https://github.com/QMUI/LookinServer/blob/master/Src/Server/Others/LKS_TraceManager.m#L152） 。

似乎可以通过 Swift 的 mirrow 相关机制实现“显示属性名”，以后有时间时会研究。
