### ISSUE TITLE
Bug？？？

### ISSUE THREAD

**Issue by a51095** [QMUI/LookinServer#63]
当前工程正常，视图展示及其事件均正常；
**问题现象**
- 1）通过手动方式导入，Lookin可以正常使用；
- 2）通过CocoaPod方式导入，Lookin展示视图异常，出现两个“UIWindowLayer”层级混乱；
- 3）如图所示，麻烦排查修复一下；
<img width="354" alt="截屏2021-08-23 15 39 45" src="https://user-images.githubusercontent.com/29021369/130411205-4dff2d87-e03a-4a71-8867-048776e28166.png">

**Comment by 183959633** [comment]
并且，所有层级视图，不显示类名，仅仅显示“CALayer”
<img width="336" alt="截屏2021-08-23 16 01 21" src="https://user-images.githubusercontent.com/29021369/130412323-0a381de3-a91a-4347-a79e-6e7f4378c311.png">

**Comment by hughkli** [comment]
“通过手动方式导入，Lookin可以正常使用，使用 CocoaPods 导入有问题
- 因为手动导入的 LookinServer 是 1.0.0 版本，而 CocoaPods 的 LookinServer 已经更新到了 1.0.4，所以可能是 1.0.1 ～ 1.0.4 的某个升级引入的 bug。

有两种方法可以调试：
1）构建一个可以重现该 bug 的 iOS 项目发给我
2）在 https://github.com/QMUI/LookinServer/blob/master/Src/Server/Category/UIView%2BLookinServer.m#L32 这里打个断点，然后重启你的 iOS 项目，试试看能不能成功走进这个断点里面

**Comment by 183959633** [comment]
**感谢解答**
我现在能够提供的协助如下：

- 1）在上诉“32”行断点，没有进来；
- 2）自己创建的demo工程，无论手动方式还是cocoapods方式，Lookin均正常工作；
- 3）初步猜测，是项目工程问题，这个项目工程结构比较复杂，有多个target，且大量引入三方SDK及自己项目组写的组件；

**Comment by hughkli** [comment]
你可以依次尝试：
1）先确保把手动导入的 LookinServer 删掉，clean 一下 project，然后使用 cocoapods 的 LookinServer ，试试是否仍然有这个问题
（因为我怕你无意间同时使用了两份 framework 导致异常，而且这几个版本确实没有改相关的代码）

2）看看上述 32 行的 hook 为啥失败了，通常是由于你们最近引入的一些库使用了不标准的 hook 代码导致 LookinServer 的 hook 失效了。
（当然了，LookinServer 自身的 hook 也不是很标准，会在以后的版本里修改，不过这都是后话了……）
