### ISSUE TITLE
Help: 如何在 M1 Mac 上使用断点方式调试

### ISSUE THREAD

**Issue by cuzv** [QMUI/LookinServer#65]
按照如下官网提供的方法，Intel 芯片可以正常使用，但是 M1 Mac 却无法使用
https://lookin.work/faq/integration-breakpoint/

使用 CocoaPods 集成源码到项目中，可以正常使用。所以猜测应该是 Mac App 提供的 LookinServer.framework 不支持 M1，但是官网提供的下载链接是 1.0.0 版本的。

不知道是否可以提供一个集成了支持 M1 版本的包（Mac App）以供下载使用？

**Comment by hughkli** [comment]
@cuzv 在该 Github 仓库的 master 分支根目录有个 LookinServer.framework 文件：https://github.com/QMUI/LookinServer/tree/master/LookinServer.framework

你把这个文件下载下来，替换你电脑上自带的 /Applications/Lookin.app/Contents/Resources/LookinServerFramework/LookinServer.framework ，然后就可以了

**Comment by cuzv** [comment]
@hughkli 感谢，已经可以正常使用了。
