### ISSUE TITLE
Pollute Production when Using SPM

### ISSUE THREAD

**Issue by iAugux** [QMUI/LookinServer#69]
hi @hughkli,

there was a safe guard 👇  to prevent the lib from running in production, any reason why it's got deleted? 🙏 

`.define("CAN_COMPILE_LOOKIN_SERVER", .when(configuration: .debug)),`

https://github.com/QMUI/LookinServer/commit/5db6488a859185bcfc90a2febf1b5d42cc690856#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eL49

**Comment by hughkli** [comment]
The guard was added back in latest v1.0.9 release.
