### ISSUE TITLE
如何在 AppCode 中设置 breakpoint

### ISSUE THREAD

**Issue by haven2world** [QMUI/LookinServer#75]
非常感谢该项目的参与者制作出这么好用的工具，之前我在 XCode 中用起来也很方便，我现在在用 AppCode （JetBrains 家的一个 iOS 开发 IDE），它的 breakpoint 设置和 XCode 有点不一样。想问下这边怎么配置才能用 BreakPoint 来 work 起来。

AppCode 的 BreakPoint 配置截图：
![image](https://user-images.githubusercontent.com/17299418/143806009-c3d38e00-b0b2-4268-aaa1-4f03a2546cca.png)

我按照 XCode 的方式配置报错：
![image](https://user-images.githubusercontent.com/17299418/143806062-6a4591ac-34c8-4883-871d-c25334872db1.png)

**Comment by starFelix** [comment]
你可以试试直接使用 dlopen 那段, 不加判断.

**Comment by hughkli** [comment]
最新版 Lookin 和 LookinServer 不支持通过断点方式集成了（因为 Xcode 更新了 Framework 打包相关机制，而我不知道怎么适配）
