### ISSUE TITLE
M1 pro报错

### ISSUE THREAD

**Issue by pengyouyoupeng** [QMUI/LookinServer#77]
building for iOS Simulator, but linking in dylib built for iOS, file 'xxx/LookinServer.framework/LookinServer' for architecture arm64
,这个怎么解决

**Comment by SKCodeing** [comment]
buildsetting 里 Validate Workspace  = YES

**Comment by hughkli** [comment]
最新版本的 LookinServer 没有问题了，因为改成了源码引入。
