### ISSUE TITLE
预览页面一片空白

### ISSUE THREAD

**Issue by lxxxzzz** [QMUI/LookinServer#78]
版本:1.0.3
问题描述：在特定的一个页面一片黑，切换2D和3D时会出来一下然后又隐藏掉了。
Xcode控制台输出：
[Unknown process name] CGContextSaveGState: invalid context 0x0. Backtrace:
  <<redacted>+440>
   <-[CALayer(LookinServer) lks_soloScreenshotWithLowQuality:]+1276>
    <__55-[LKS_HierarchyDetailsHandler _dequeueAndHandlePackage]_block_invoke_2+800>
     <__30-[NSArray(Lookin) lookin_map:]_block_invoke+84>
      <<redacted>+16>
       <<redacted>+152>
        <-[NSArray(Lookin) lookin_map:]+340>
         <__55-[LKS_HierarchyDetailsHandler _dequeueAndHandlePackage]_block_invoke+240>
          <_dispatch_call_block_and_release+24>
           <_dispatch_client_callout+16>
            <_dispatch_main_queue_callback_4CF+944>
             <<redacted>+12>
              <<redacted>+2528>
               <CFRunLoopRunSpecific+572>
                <GSEventRunModal+160>
                 <<redacted>+1080>
                  <UIApplicationMain+2028>
                   <main+128>                    103414190

**Comment by hughkli** [comment]
把 LookinServer 升到最新的 1.0.4 即可



&nbsp;


------------------ 原始邮件 ------------------
发件人: 小小 ***@***.***&gt;
发送时间: 2022年1月19日 11:54
收件人: QMUI/LookinServer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[QMUI/LookinServer] 1.0.3渲染问题 (Issue #78)





 
版本:1.0.3
 问题描述：在某一个页面一片空白，切换2D和3D时会出来一下然后又隐藏掉了。
 Xcode控制台输出：
 [Unknown process name] CGContextSaveGState: invalid context 0x0. Backtrace:
 <+440&gt;
 <-[CALayer(LookinServer) lks_soloScreenshotWithLowQuality:]+1276&gt;
 <__55-[LKS_HierarchyDetailsHandler _dequeueAndHandlePackage]_block_invoke_2+800&gt;
 <__30-[NSArray(Lookin) lookin_map:]_block_invoke+84&gt;
 <+16&gt;
 <+152&gt;
 <-[NSArray(Lookin) lookin_map:]+340&gt;
 <__55-[LKS_HierarchyDetailsHandler _dequeueAndHandlePackage]_block_invoke+240&gt;
 <_dispatch_call_block_and_release+24&gt;
 <_dispatch_client_callout+16&gt;
 <_dispatch_main_queue_callback_4CF+944&gt;
 <+12&gt;
 <+2528&gt;
 <CFRunLoopRunSpecific+572&gt;
 <GSEventRunModal+160&gt;
 <+1080&gt;
 <UIApplicationMain+2028&gt;
 <main+128&gt;                    103414190
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
