### ISSUE TITLE
M1  arch -x86_64 pod install  失败

### ISSUE THREAD

**Issue by Butterfly7777777** [QMUI/LookinServer#82]
[!] Error installing LookinServer
[!] /usr/bin/git clone https://github.com/QMUI/LookinServer.git /var/folders/wz/rynv_m6d05dgms6_lvpczg1h0000gn/T/d20220209-49637-4rp7u2 --template= --single-branch --depth 1 --branch 1.0.4

Cloning into '/var/folders/wz/rynv_m6d05dgms6_lvpczg1h0000gn/T/d20220209-49637-4rp7u2'...
fatal: repository 'https://github.com.cnpmjs.org/QMUI/LookinServer.git/' not found

**Comment by hughkli** [comment]
看起来是你使用的这个 cnpmjs.org 网站没有收录 https://github.com/QMUI/LookinServer.git？
