### ISSUE TITLE
How to open parameteers back?

### ISSUE THREAD

**Issue by bimawa** [QMUI/LookinServer#84]
I hide some params and now can't find how to make it show again?
![CleanShot 2022-02-18 at 22 11 08](https://user-images.githubusercontent.com/1393809/154730012-83146712-7856-4fb5-84b8-7579fe22e64e.png)

**Comment by bimawa** [comment]
CleanMyMac solve this issue...

**Comment by hughkli** [comment]
Update Lookin to latest version (1.0.1) to fix this bug.
