### ISSUE TITLE
怎么查看任意APP的UI

### ISSUE THREAD

**Issue by CoderLGL** [QMUI/LookinServer#9]

**Comment by hughkli** [comment]
可在 Github 里搜索 “LookinLoader”

------------------ 原始邮件 ------------------
发件人: 李光亮 <notifications@github.com&gt;
发送时间: 2019年8月31日 14:02
收件人: QMUI/LookinServer <LookinServer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[QMUI/LookinServer] 怎么查看任意APP的UI (#9)
