### ISSUE TITLE
Any workflow about SwiftUI?

### ISSUE THREAD

**Issue by YaphetS1** [QMUI/LookinServer#93]
This is really hot issue. I'm not one with that :-( Standard workflows not working

**Comment by xcwxcw91** [comment]
@YaphetS1 
This library works fine with Swift and SwiftUI.
My project is a workspace linking  project target and pod target, I added swiftPM also and it works fine.

![截屏2022-05-17 18 22 03](https://user-images.githubusercontent.com/26263918/168789884-78dd745e-7d85-4c73-a272-a56d847b0a7e.png)

**Comment by hstdt** [comment]
Is it possible for more detail info from SwiftUI, such as text font.

https://github.com/nalexn/ViewInspector
