### ISSUE TITLE
不能正确支持阿语（从右往左）的UI布局

### ISSUE THREAD

**Issue by dourgulf** [QMUI/LookinServer#97]
RT
iOS客户端使用阿拉伯语，Lookin看到的UI布局和iOS真正的布局是不一样的

**Comment by hughkli** [comment]
可以分别给 Lookin 和 iOS 客户端截个图看看吗？

**Comment by dourgulf** [comment]
应该是搞错了，iOS约束有错误的时候看到不对，约束正确的时候看到是一致的。我关闭了。
