### ISSUE TITLE
iOS 16.0  模拟器 crash

### ISSUE THREAD

**Issue by sunimp** [QMUI/LookinServer#98]
环境：
电脑：M1 Pro MBP
Xcode: 14.0 beta2
模拟器：iOS 16.0

<img width="1593" alt="image" src="https://user-images.githubusercontent.com/16975429/177236299-c3077f45-fb5f-4e9f-bc53-02fe78e8e322.png">

**Comment by hughkli** [comment]
之前也遇到过类似的，不过没有可重现的 Demo 的话很难查。

你可以先把这个代码注释掉，我也可以在未来的版本中提供一个配置选项，允许用户临时把这个 ivar 相关的 feature（显示变量名）关掉以规避 Crash。
