### ISSUE TITLE
Integration via breakpoint

### ISSUE THREAD

**Issue by eugeniobaglieri** [QMUI/LookinServer#99]
Hi, i just noticed that integration guide doesn't mention anymore the integration via Xcode breakpoint.
Is this method still valid? If yes, why is no more mentioned?
Googling i found this unlinked page [https://lookin.work/faq/integration-breakpoint/](url)
Thank you.

**Comment by hughkli** [comment]
"Integration via breakpoint" was only valid with Lookin 1.0.0 and mac with Intel chip, so I removed page.
To enable this feature again, I need to spend time to learn how to make LookinServer.xcframework instead of LookinServer.framework. But unfortunately I don't have such time nowadays.

**Comment by muyexi** [comment]
@hughkli Creating xcframework is a lot easier now with http://github.com/giginet/Scipio. I created one with Scipio, but somehow it still doesn't work. Do you know what's wrong?

> expr (Class)NSClassFromString(@"Lookin") == nil ? (void *)dlopen("/LookinServer/XCFrameworks/LookinServer.xcframework/ios-arm64/LookinServer.framework/LookinServer", 0x2) : ((void*)0)

[LookinServer.xcframework.zip](https://github.com/user-attachments/files/19580842/LookinServer.xcframework.zip)
